### ISSUE TITLE
How to?

### ISSUE THREAD

**Issue by mojbuk** [sajjad0321/iptv#1]
Best regards. How use this source code?
I try import and open but have more errors?

**Comment by sajjad0321** [comment]
Download & open in Android Studio Sync Gradle and other dependencies ☺

**Comment by mojbuk** [comment]
Thank you. Not work. 
I have errors like: 
Error:(73, 41) error: cannot find symbol class Login

**Comment by sajjad0321** [comment]
if you can contribute to this proj i can help Like "Make this App better"

**Comment by raiarainne** [comment]
How are you?
I am getting an error as following when i use a .m3u file.
08-07 01:04:08.594 20566-20566/? D/error: length=14; regionStart=0; regionLength=-1

This is the m3u file what i use in app.
http://links.nextip.biz:8585/get.php?username=n0SVnMJotH&password=jMhrpaSV7T&type=m3u_plus&output=ts
Please give me solution.
Thank you
