### ISSUE TITLE
Parse Issue

### ISSUE THREAD

**Issue by raiarainne** [sajjad0321/iptv#2]
How are you?
I am getting an error as following when i use a .m3u file.
08-07 01:04:08.594 20566-20566/? D/error: length=14; regionStart=0; regionLength=-1

This is the m3u file what i use in app.
http://links.nextip.biz:8585/get.php?username=n0SVnMJotH&password=jMhrpaSV7T&type=m3u_plus&output=ts

And this is a part of my code what the issue is occurred .
 try {
            //is = getAssets().open("tv_channels.m3u");

            File file = new File("/storage/emulated/0/Android/tv_test.m3u");
          // is= new FileInputStream(file);
            is=getContentResolver().openInputStream(Uri.fromFile(file));

            M3UPlaylist playlist = parser.parseFile(is);
            mPlaylistParams.setText(playlist.getPlaylistParams());
            mAdapter.update(playlist.getPlaylistItems());
        } catch (Exception e) {            
            Log.d("error", e.getMessage());
        }

Please give me solution.
Thank you

**Comment by sajjad0321** [comment]
where r u placing m3u file

**Comment by raiarainne** [comment]
I placed the m3u file in device storage.
And i am calling that through uri.
And this part is working correctly.

**Comment by sajjad0321** [comment]
Okay then whats the issue ??

**Comment by raiarainne** [comment]
Thank you for your reply.
I can read only channel name and categories in the m3u file.
I need to read channel url and logo url.
So this part is not working for me.
Thank you

**Comment by sajjad0321** [comment]
Okay. I have removed that part showing channel url below channel name. 
& i'll fix logo url

**Comment by sajjad0321** [comment]
& if u have time. Contribute to this proj to make it Awesome App.
Thanks

**Comment by raiarainne** [comment]
Okay
Let me try .
I am trying to fix this issue in my end.
If i have any solution. I will notify you soon.
See you later

**Comment by sajjad0321** [comment]
Okay

**Comment by sajjad0321** [comment]
Fixed ???
