### ISSUE TITLE
can't build..

### ISSUE THREAD

**Issue by techker** [sajjad0321/iptv#5]
hey guys i tried to build it but it seems in bad shape..missing class login and the json file..
can i get help on this?

**Comment by sajjad0321** [comment]
u can get ur json file via connecting it to ur firebase google account then it'll get new json file.

**Comment by afielden** [comment]
It's ok, that class does exist in your repository, but the downloaded zip file doesn't include it.

**Comment by techker** [comment]
ya connected to git, download a google.jdk and also changed the path in the gradle file.

sync and seems good.just need to figure out what to change to point to my server
